### PR TITLE
Loc string bixes

### PR DESCRIPTION
**Pull request by diamante0018**
blocked by #12  

This moves all the localized strings *AWAY* from an iwd back to a fastfile. Not only does this seriously speed up by several hundred milliseconds of the loading but it also fixes an issue in which sometimes the strings would not load at all from raw.

### CODE REVIEW

**Comment by diamante0018** [comment]
Unfortunately, the changes made by this PR could break people with russian games. Too bad!

**Comment by diamante0018** [comment]
Can be merged after this issue is resolved https://github.com/iw4x/iw4x-client/issues/77

**Comment by Rackover** [comment]
So uh since https://github.com/iw4x/iw4x-client/issues/77 is closed what do we do here

**Comment by Rackover** [comment]
PR Looks good otherwise i'd be ready to test it

**Comment by diamante0018** [comment]
> PR Looks good otherwise i'd be ready to test it

I agree

**Review by Rackover — APPROVED** [review]

**Pull request merged**
