### PR TITLE
fix: Removed hardcoded max xpScale.

### PR DESCRIPTION
**Pull request by efinst0rm**

### CODE REVIEW

**Comment by efinst0rm** [comment]
@Rackover I ended switching this to clamp to prevent it possibly overflowing. Like we talked about it in discord

**Comment by Rackover** [comment]
wait didn't you want to remove the max xpscale? Why add back a clamp then?

**Comment by efinst0rm** [comment]
Originally the idea was to remove this hard limit.

	if ( level.xpScale > 4 || level.xpScale < 0)
		exitLevel( false );

**Comment by diamante0018** [comment]
Two things I have noticed after a user reported getting pranked by exit level:

IW scripter(s) made a mistake as their own code is in direct contradiction: Both the original code and the current code after this PR allow the game to kill itself if you set scr_xpscale to 0 (you get 0 points for a kill).

The second theoretical IW scripter was more aware of this and edited the function at the bottom (st0rm or myself did not notice at the time) here: https://github.com/efinst0rm/iw4x-rawfiles-current/blob/cda452c8b6eedbacab4dae04c66402c98e74de96/iw4x/iw4x_00/maps/mp/gametypes/_rank.gsc#L753
If the dvar is 0 or less the level exits. if it's greater than that it also kills itself

```diff
-level.xpscale = max( level.xpscale, 0 );
+level.xpscale = max( level.xpscale, 1 );
```

Also remove the checks at the bottom, like here.
https://git.alterware.dev/alterware/iw5-rawfiles/src/branch/master/raw/scripts/mp/_patches.gsc#L124

I never bothered to think about clamping the value's upper bound because the game can just take even a multiplier of 1000. It's up to whoever decides to rewrite this patch if they want to put an upper limit as well but at least do not allow anything lower than 1

**Pull request merged**
